# Generated by Django 5.1.1 on 2024-09-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_cart_products_cartproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='api.CartProduct', to='api.pizza'),
        ),
    ]
